# Student Performance Factors

In [142]:
import pandas as pd
import numpy as np

from bokeh.io import output_notebook
from bokeh.plotting import figure, show
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [143]:
#@title Loading data

LoadCsv = 'https://raw.githubusercontent.com/Ashraful332/Scikit-learn/main/data/SPF/StudentPerformanceFactors.csv'
data = pd.read_csv(LoadCsv)
data.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

## Graph

In [144]:
output_notebook()

In [145]:
#@title Basic Graph
p = figure(width=400, height=400)

# add a scatter circle renderer with a size, color, and alpha
p.scatter([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

# show the results
show(p)

In [146]:
#@title Hours_Studied to Exam_Score

p = figure(title="Hours Studied vs Exam Score",width=400, height=400)

p.scatter(data['Hours_Studied'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Hours_Studied"
p.yaxis.axis_label = "Exam Score"

show(p)

In [147]:
#@title Attendance vs Exam_Score
p = figure(title="Attendance vs Exam Score",width=400, height=400)

p.scatter(data['Attendance'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Attendance"
p.yaxis.axis_label = "Exam Score"

show(p)

In [148]:

Family_Income = data['Family_Income'].unique()
Exam_Score = data['Exam_Score']

p = figure(x_range=Family_Income, height=350, title="Family Income vs Exam Score",
           toolbar_location=None, tools="")

p.vbar(x=Family_Income, top=Exam_Score, width=0.9)

p.xgrid.grid_line_color = None
p.y_range.start = 0

p.xaxis.axis_label = "Family Income"
p.yaxis.axis_label = "Exam Score"

show(p)

BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('top', 6607), ('x', 3)

In [149]:
#@title Sleep_Hours vs Exam Score
p = figure(title="Sleep Hours vs Exam Score",width=400, height=400)

p.scatter(data['Sleep_Hours'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Sleep_Hours"
p.yaxis.axis_label = "Exam Score"

show(p)

# Train Model

In [150]:
data = pd.read_csv(LoadCsv)
data.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [151]:
# convert Parental_Involvement Low Medium High into 0 1 2
data['Parental_Involvement'] = data['Parental_Involvement'].map({
    "Low":0,
    "Medium":1,
    "High":2
})

In [152]:
data['Parental_Involvement'].head()

0    0
1    0
2    1
3    0
4    1
Name: Parental_Involvement, dtype: int64

In [153]:
# convert Access_to_Resources Low Medium High into 0 1 2
data['Access_to_Resources'] = data['Access_to_Resources'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
data['Access_to_Resources'].head()

0    2
1    1
2    1
3    1
4    1
Name: Access_to_Resources, dtype: int64

In [154]:
# convert Extracurricular_Activities Yes/No into 1/0
data["Extracurricular_Activities"] = data["Extracurricular_Activities"].map({
    "No": 0,
    "Yes": 1
})
data["Extracurricular_Activities"].head()

0    0
1    0
2    1
3    1
4    1
Name: Extracurricular_Activities, dtype: int64

In [155]:
# convert Motivation_Level Low Medium High into 0 1 2
data['Motivation_Level'] = data['Motivation_Level'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
data['Motivation_Level'].head()

0    0
1    0
2    1
3    1
4    1
Name: Motivation_Level, dtype: int64

In [156]:
# convert Internet_Access Yes/No into 1/0
data["Internet_Access"] = data["Internet_Access"].map({
    "No": 0,
    "Yes": 1
})
data["Internet_Access"].head()

0    1
1    1
2    1
3    1
4    1
Name: Internet_Access, dtype: int64

In [157]:
# convert Family_Income Low Medium High into 0 1 2
data['Family_Income'] = data['Family_Income'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
data['Family_Income'].head()

0    0
1    1
2    1
3    1
4    1
Name: Family_Income, dtype: int64

In [158]:
# convert Teacher_Quality Low Medium High into 0 1 2
data['Teacher_Quality'] = data['Teacher_Quality'].map({
    "Low":0,
    "Medium":1,
    "High":2
}).astype('Int64')
data['Teacher_Quality'].head()

0    1
1    1
2    1
3    1
4    2
Name: Teacher_Quality, dtype: Int64

In [159]:
# convert School_Type Public/Private into 1/0
data["School_Type"] = data["School_Type"].map({
    "Public": 0,
    "Private": 1
})
data["School_Type"].head()

0    0
1    0
2    0
3    0
4    0
Name: School_Type, dtype: int64

In [160]:
# convert Peer_Influence Low Medium High into 0 1 2
data['Peer_Influence'] = data['Peer_Influence'].map({
    "Negative":0,
    "Positive":1,
    "Neutral":2
})
data['Peer_Influence'].head()

0    1
1    0
2    2
3    0
4    2
Name: Peer_Influence, dtype: int64

In [161]:
# convert Learning_Disabilities Yes/No into 1/0
data["Learning_Disabilities"] = data["Learning_Disabilities"].map({
    "No": 0,
    "Yes": 1
})
data["Learning_Disabilities"].head()

0    0
1    0
2    0
3    0
4    0
Name: Learning_Disabilities, dtype: int64

In [162]:
# convert Parental_Education_Level Low Medium High into 0 1 2
data['Parental_Education_Level'] = data['Parental_Education_Level'].map({
    "High School":0,
    "College":1,
    "Postgraduate":2
}).astype('Int64')
data['Parental_Education_Level'].head()

0    0
1    1
2    2
3    0
4    1
Name: Parental_Education_Level, dtype: Int64

In [163]:
# convert Distance_from_Home Low Medium High into 0 1 2
data['Distance_from_Home'] = data['Distance_from_Home'].map({
    "Near":0,
    "Moderate":1,
    "Far":2
}).astype('Int64')
data['Distance_from_Home'].head()

0    0
1    1
2    0
3    1
4    0
Name: Distance_from_Home, dtype: Int64

In [164]:
# convert Gender Yes/No into 1/0
data["Gender"] = data["Gender"].map({
    "Male": 0,
    "Female": 1
})
data["Gender"].head()

0    0
1    1
2    0
3    0
4    1
Name: Gender, dtype: int64

## Training Model

In [165]:
data['Exam_Score']

0       67
1       61
2       74
3       71
4       70
        ..
6602    68
6603    69
6604    68
6605    68
6606    64
Name: Exam_Score, Length: 6607, dtype: int64

In [166]:
# @title Working Simple code

# Drop rows with any NaN values
data.dropna(inplace=True)

# Features
X = data[[
    "Hours_Studied",	"Attendance",	"Parental_Involvement",	"Access_to_Resources",	"Extracurricular_Activities",
    "Sleep_Hours",	"Previous_Scores",	"Motivation_Level",	"Internet_Access",	"Tutoring_Sessions",	"Family_Income",
    "Teacher_Quality",	"School_Type",	"Peer_Influence",	"Physical_Activity",	"Learning_Disabilities",
    "Parental_Education_Level",	"Distance_from_Home",	"Gender"
]]

# Target
y = data['Exam_Score']

# Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Set Model
model = LinearRegression()

# Train Model
model.fit(X_train, y_train)

print("Training Complete!")

# =========================
# SAVE MODEL
# =========================

joblib.dump(model, "student_placement_model.pkl")

print("Model saved!")

Training Complete!
Model saved!

# Predict Model

In [167]:
data.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0,2,0,7,73,0,1,0,0,1,0,1,3,0,0,0,0,67
1,19,64,0,1,0,8,59,0,1,2,1,1,0,0,4,0,1,1,1,61
2,24,98,1,1,1,7,91,1,1,2,1,1,0,2,4,0,2,0,0,74
3,29,89,0,1,1,8,98,1,1,1,1,1,0,0,4,0,0,1,0,71
4,19,92,1,1,1,6,65,1,1,3,1,2,0,2,4,0,1,0,1,70

In [168]:
# Load Save Model
def load_model(model_path):
    model = joblib.load(model_path)
    print("Model loaded!")
    return model
# load_model("student_placement_model.pkl")



# Predict new student placement
# The input array had 20 features, but the model expects 19.
# Removed the leading '0' to match the 19 features: Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender.
result = model.predict([[
    23,	84,	0,	2,	0,	7,	73,	0,	1,	0,	0,	1,	0,	1,	3,	0,	0,	0,	0
]])

print("Prediction:", result)

Prediction: [66.55777928]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

## Predict Model with test.csv file

In [169]:
#@title Loading test data

LoadTrainCsv = 'https://raw.githubusercontent.com/Ashraful332/Scikit-learn/main/data/SPF/test.csv'
TrainData = pd.read_csv(LoadTrainCsv)
TrainData.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,NaN
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,NaN
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,NaN
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,NaN
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,NaN

In [170]:
#@title Convert string TrainData into number

# convert Parental_Involvement Low Medium High into 0 1 2
TrainData['Parental_Involvement'] = TrainData['Parental_Involvement'].map({
    "Low":0,
    "Medium":1,
    "High":2
})

TrainData['Parental_Involvement'].head()

# convert Access_to_Resources Low Medium High into 0 1 2
TrainData['Access_to_Resources'] = TrainData['Access_to_Resources'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
TrainData['Access_to_Resources'].head()

# convert Extracurricular_Activities Yes/No into 1/0
TrainData["Extracurricular_Activities"] = TrainData["Extracurricular_Activities"].map({
    "No": 0,
    "Yes": 1
})
TrainData["Extracurricular_Activities"].head()

# convert Motivation_Level Low Medium High into 0 1 2
TrainData['Motivation_Level'] = TrainData['Motivation_Level'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
TrainData['Motivation_Level'].head()

# convert Internet_Access Yes/No into 1/0
TrainData["Internet_Access"] = TrainData["Internet_Access"].map({
    "No": 0,
    "Yes": 1
})
TrainData["Internet_Access"].head()

# convert Family_Income Low Medium High into 0 1 2
TrainData['Family_Income'] = TrainData['Family_Income'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
TrainData['Family_Income'].head()

# convert Teacher_Quality Low Medium High into 0 1 2
TrainData['Teacher_Quality'] = TrainData['Teacher_Quality'].map({
    "Low":0,
    "Medium":1,
    "High":2
}).astype('Int64')
TrainData['Teacher_Quality'].head()

# convert School_Type Public/Private into 1/0
TrainData["School_Type"] = TrainData["School_Type"].map({
    "Public": 0,
    "Private": 1
})
TrainData["School_Type"].head()

# convert Peer_Influence Low Medium High into 0 1 2
TrainData['Peer_Influence'] = TrainData['Peer_Influence'].map({
    "Negative":0,
    "Positive":1,
    "Neutral":2
})
TrainData['Peer_Influence'].head()

# convert Learning_Disabilities Yes/No into 1/0
TrainData["Learning_Disabilities"] = TrainData["Learning_Disabilities"].map({
    "No": 0,
    "Yes": 1
})
TrainData["Learning_Disabilities"].head()

# convert Parental_Education_Level Low Medium High into 0 1 2
TrainData['Parental_Education_Level'] = TrainData['Parental_Education_Level'].map({
    "High School":0,
    "College":1,
    "Postgraduate":2
}).astype('Int64')
TrainData['Parental_Education_Level'].head()

# convert Distance_from_Home Low Medium High into 0 1 2
TrainData['Distance_from_Home'] = TrainData['Distance_from_Home'].map({
    "Near":0,
    "Moderate":1,
    "Far":2
}).astype('Int64')
TrainData['Distance_from_Home'].head()

# convert Gender Yes/No into 1/0
TrainData["Gender"] = TrainData["Gender"].map({
    "Male": 0,
    "Female": 1
})
TrainData["Gender"].head()

0    0
1    1
2    0
3    0
4    1
Name: Gender, dtype: int64

In [171]:
# Replaces NaNs as 0
TrainData['Exam_Score'] = TrainData['Exam_Score'].fillna(0).astype('Int64')

In [172]:
TrainData.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0,2,0,7,73,0,1,0,0,1,0,1,3,0,0,0,0,0
1,19,64,0,1,0,8,59,0,1,2,1,1,0,0,4,0,1,1,1,0
2,24,98,1,1,1,7,91,1,1,2,1,1,0,2,4,0,2,0,0,0
3,29,89,0,1,1,8,98,1,1,1,1,1,0,0,4,0,0,1,0,0
4,19,92,1,1,1,6,65,1,1,3,1,2,0,2,4,0,1,0,1,0

In [173]:
#@title Test CSV file

# Load model
model = joblib.load("student_placement_model.pkl")

test_data = TrainData

# Drop rows with any NaN values to handle potential NaNs introduced during mapping
test_data.dropna(inplace=True)

# 3. Separate feature columns from the target column
X_test = test_data.drop(columns=["Exam_Score"])

# 4. Generate predictions
predicted_scores = model.predict(X_test)

# 5. Fill the Exam_Score column with the model's predictions
test_data["Exam_Score"] = predicted_scores

# 6. Export the updated dataset to a new CSV file
test_data.to_csv("test_with_predictions.csv", index=False)

print("Predictions filled and saved to 'test_with_predictions.csv'")

Predictions filled and saved to 'test_with_predictions.csv'